apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "zabbix-server-mysql.fullname" . }}
  labels:
    app: "{{ template "zabbix-server-mysql.fullname" . }}"
    chart: "{{ template "zabbix-server-mysql.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: "{{ template "zabbix-server-mysql.fullname" . }}"
      release: {{ .Release.Name | quote }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "zabbix-server-mysql.fullname" . }}"
        chart: "{{ template "zabbix-server-mysql.chart" . }}"
        release: {{ .Release.Name | quote }}
{{- if or .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      containers:
      - name: zabbix-server-mysql
        image: {{ template "zabbix-server-mysql.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: DB_SERVER_HOST
          value: {{ template "mariadb.fullname" . }}
        - name: DB_SERVER_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: {{ .Values.mariadb.db.name | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mariadb.db.user | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mariadb.fullname" . }}
              key: mariadb-password
        ports:
        - name: zabbix-trapper
          containerPort: 10051
        volumeMounts:
        {{- if .Values.persistence.alertscripts.enabled }}
        - mountPath: /var/lib/zabbix/alertscripts
          name: alertscripts
        {{- end }}
        {{- if .Values.persistence.externalscripts.enabled }}
        - mountPath: /var/lib/zabbix/externalscripts
          name: externalscripts
        {{- end }}
        {{- if .Values.persistence.enc.enabled }}
        - mountPath: /var/lib/zabbix/enc
          name: enc
        {{- end }}
        {{- if .Values.persistence.mibs.enabled }}
        - mountPath: /var/lib/zabbix/mibs
          name: mibs
        {{- end }}
        {{- if .Values.persistence.modules.enabled }}
        - mountPath: /var/lib/zabbix/modules
          name: modules
        {{- end }}
        {{- if .Values.persistence.snmptraps.enabled }}
        - mountPath: /var/lib/zabbix/snmptraps
          name: snmptraps
        {{- end }}
        {{- if .Values.persistence.ssh_keys.enabled }}
        - mountPath: /var/lib/zabbix/ssh_keys
          name: ssh-keys
        {{- end }}
        {{- if .Values.persistence.ssl.certs.enabled }}
        - mountPath: /var/lib/zabbix/ssl/certs
          name: ssl-certs
        {{- end }}
        {{- if .Values.persistence.ssl.keys.enabled }}
        - mountPath: /var/lib/zabbix/ssl/keys
          name: ssl-keys
        {{- end }}
        {{- if .Values.persistence.ssl.ssl_ca.enabled }}
        - mountPath: /var/lib/zabbix/ssl/ssl_ca
          name: ssl-ssl-ca
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: alertscripts
      {{- if .Values.persistence.alertscripts.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.alertscripts.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: externalscripts
      {{- if .Values.persistence.externalscripts.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.externalscripts.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: enc
      {{- if .Values.persistence.enc.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.enc.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: mibs
      {{- if .Values.persistence.mibs.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.mibs.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: modules
      {{- if .Values.persistence.modules.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.modules.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: snmptraps
      {{- if .Values.persistence.snmptraps.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.snmptraps.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: ssh-keys
      {{- if .Values.persistence.ssh_keys.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.ssh_keys.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: ssl-certs
      {{- if .Values.persistence.ssl.certs.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.ssl.certs.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: ssl-keys
      {{- if .Values.persistence.ssl.keys.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.ssl.keys.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: ssl-ssl-ca
      {{- if .Values.persistence.ssl.ssl_ca.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.ssl.ssl_ca.claimName }}
      {{- else }}
        emptyDir: {}
      {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end -}}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
